name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Only deploy after a PR is merged into main

permissions:
  contents: write  # Required to push to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # This assumes index.html is in root
